name: cicd.yml

on:
  push:
    branches:
      - main

jobs:
  user-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: user-service
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: temurin
      - name: Build User-Service
        run: |
#          cd user-service
          mvn clean package -DskipTests
      - name: Run Tests
        run: |
#          cd user-service
          mvn test
      - name: Build Docker Image
        run: |
#          cd user-service/docker
          docker build -t user/service:1.0.0 .
          docker tag user/service:1.0.0 lakshaybxt/user-service:1.0.0

      - name: Push Docker Image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push lakshaybxt/user-service:1.0.0
#      - name: Deploy on EC2
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_SSH_KEY }}