name: cicd.yml

on:
  push:
    branches:
      - main

jobs:
  auth-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-jdk@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Build Docker Image
        run: |
          docker build -t auth-service:1.0.0 .
          docker tag auth-service:1.0.0 lakshaybxt/auth-service:1.0.0

      - name: Push Docker Image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        run: docker push lakshaybxt/auth-service:1.0.0

#      - name: Deploy on EC2
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_SSH_KEY }}