name: pipeline-backend.yml

on:
  push:
    branches:
      - main

jobs:
  auth-service:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: userdb
          POSTGRES_USER: userdb
          POSTGRES_PASSWORD: changemeinprod!
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Build Docker Image
        run: |
          docker build -t auth-service:1.0.0 .
          docker tag auth-service:1.0.0 lakshaybxt/auth-service:1.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        run: docker push lakshaybxt/auth-service:1.0.0

#      - name: Deploy on EC2
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#            docker pull lakshaybxt/auth-service:1.0.0
#            docker stop my-service || true
#            docker rm my-service || true
#            docker run -d -p 8080:8080 --name auth-service --rm lakshaybxt/auth-service:1.0.0